# Cloudflare Pages configuration
name = "plumbersbournemouth247-co-uk"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-20"

[[d1_databases]]
binding = "DB"
database_name = "bournemouth-leads"
database_id = "640a6f4a-c517-477e-afad-a6b39ffbcf68"
